name : Update Forex News Calendar

on:
  schedule:
    - cron: "0 3 * * *"  # every day at 03:00 UTC
  workflow_dispatch:

jobs:
  fetch-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download new .ics calendar
        run: |
          curl -L "https://www.forexfactory.com/calendar.ics" -o calendar.ics

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add calendar.ics
          git commit -m "📅 Update calendar.ics (auto)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
